name: 'FOSSA'

on:
  schedule:
    - cron: '10 * * * *'

jobs:
  fossa-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: fossas/fossa-action@v1
        with:
          api-key: ${{secrets.fossaApiKey}}
          branch: main
